---
# tasks file for lb-tier
- name: install "{{payload}}"
  yum:
   name: "{{ payload }}"
   state: latest

- name: enable {{ payload }} at boot
  service:
   name: "{{ payload }}"
   state: started

- name: configure "{{ payload }}"
  template:
   src: haproxy.cfg.j2
   dest: /etc/haproxy/haproxy.cfg
   mode: 0644

- name: start "{{ payload }}"
  service:
   name: "{{ payload }}"
   state: restarted

